package KieRule;
import com.maersk.spring.drools.api.model.Order;

rule "Dominos"

when
orderObject : Order(franchiseName=="Dominos" && price>1250);
then
orderObject.setDiscount(10);
end;

rule "Pizzahut"

when
orderObject : Order(franchiseName=="Pizzahut" && price>1000);
then
orderObject.setDiscount(8);
end;

rule "KFC"

when
orderObject : Order(franchiseName=="KFC" && price>2000);
then
orderObject.setDiscount(15);
end;

rule "Subway"

when
orderObject : Order(franchiseName=="Subway" && price>1500);
then
orderObject.setDiscount(12);
end;